name: Wails Build

on:
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - platform: "linux/amd64"
            os: "ubuntu-latest"
          - platform: "windows/amd64"
            os: "windows-latest"
          - platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read app name from wails.json
        id: meta
        run: |
          echo "APPNAME=$(jq -r '.name' wails.json)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ steps.meta.outputs.APPNAME }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          sign: false
          go-version: "1.23.3"
          wails-version: "v2.9.2"
          node-version: "20.10.0"

      - name: Set release filename
        id: file
        run: |
          APPNAME="${{ steps.meta.outputs.APPNAME }}"
          case "${{ matrix.build.os }}" in
            ubuntu-*)
              echo "FILENAME=build/bin/$APPNAME" >> "$GITHUB_OUTPUT"
              ;;
            windows-*)
              echo "FILENAME=build/bin/$APPNAME.exe" >> "$GITHUB_OUTPUT"
              ;;
            macos-*)
              ditto -c -k --keepParent "build/bin/$APPNAME.app" "build/bin/$APPNAME.app.zip"
              echo "FILENAME=build/bin/$APPNAME.app.zip" >> "$GITHUB_OUTPUT"
              ;;
          esac
        shell: bash

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: WailsTerm ${{ github.ref_name }}
          files: ${{ steps.file.outputs.FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
